apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "machinedeployment.worker.name" . }}
  annotations:
    # Temporary fix to address https://github.com/k0sproject/k0smotron/issues/911
    machineset.cluster.x-k8s.io/skip-preflight-checks: "ControlPlaneIsStable"
spec:
  clusterName: {{ include "cluster.name" . }}
  replicas: {{ .Values.workersNumber }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
        node-role.kubernetes.io/worker-infra: ""
        node.kubernetes.io/role: worker-infra
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: {{ include "k0sworkerconfigtemplate.name" . }}
      clusterName: {{ include "cluster.name" . }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: {{ include "openstackmachinetemplate.worker.name" . }}
