apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "machinedeployment.gpul4.name" . }}
  annotations:
    # Temporary fix to address https://github.com/k0sproject/k0smotron/issues/911
    machineset.cluster.x-k8s.io/skip-preflight-checks: "ControlPlaneIsStable"
spec:
  clusterName: {{ include "cluster.name" . }}
  replicas: {{ .Values.gpuNumberL4 }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
        node-role.kubernetes.io/gpu: ""
        node.kubernetes.io/role: gpu
        node.kubernetes.io/gpu-type: "l4"
    spec:
      taints:
        - effect: NoSchedule
          key: node-role.kubernetes.io/gpu
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: {{ include "k0sworkerconfigtemplate.name" . }}
      clusterName: {{ include "cluster.name" . }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: {{ include "openstackmachinetemplate.gpul4.name" . }}